In [1]:
from zabbix_api import ZabbixAPI
from datetime import datetime
import time
import pandas as pd

In [2]:
zapi = ZabbixAPI("https://sm-fe01.webmonitor.global")
# Disable SSL certificate verification
zapi.session.verify = False
# Specify a timeout (in seconds)
zapi.timeout = 12.6
# informacoes de acesso
zapi.login("linx.rafael", "stk456rfs")
# mostra versao do zabbix
print("Connected to Zabbix API Version %s" % zapi.api_version())

Connected to Zabbix API Version 3.4.10

In [3]:
import pyodbc
import pymssql

server = 'grc-db.database.windows.net'
database = 'xct_kpidb'
username = 'grcadmin'
password = 'admin@123'
driver= 'ODBC Driver 17 for SQL Server'

In [4]:
# Construct connection string
try:
   conn = pyodbc.connect('DRIVER='+driver+';SERVER='+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+ password)
   df = pd.read_sql('select * from tb_item', conn)
   print("Connection established")
except mysql.connector.Error as err:
  if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
    print("Something is wrong with the user name or password")
  elif err.errno == errorcode.ER_BAD_DB_ERROR:
    print("Database does not exist")
  else:
    print(err)
else:
  cursor = conn.cursor()

Connection established

In [5]:
# Criar o intervalo de coleta

# time_from = time.mktime(datetime.now().timetuple()) - 60 * 60 * 24  # 1 dia (inteiro)
time_from = time.mktime(datetime.now().timetuple()) - 60 * 5  # 5 minutos

print(time_from)

1547138218.0

In [6]:
count_row = df.shape[0]  # gives number of row count
count_col = df.shape[1]  # gives number of col count

print(count_row)
print(count_col)
print(df)

109
5
     item_id  item_id_zabbix item_produto  \
0          1         2212476         MIDe
1          2         2212479         MIDe
2          3         2212481         MIDe
3          4         2212483         MIDe
4          5         2198455         MIDe
5          6         2198498         MIDe
6          7         2199995         MIDe
7          8         2198369         MIDe
8          9         2198412         MIDe
9         10         2003427         DTEF
10        11          917847     Microvix
11        12         2156697     Microvix
12        13         2184022     Microvix
13        14          878233     Microvix
14        15          878234     Microvix
15        16          878235     Microvix
16        17          878236     Microvix
17        18          878237     Microvix
18        19          878238     Microvix
19        20          878239     Microvix
20        21          878240     Microvix
21        22          878241     Microvix
22        23          878242     Microvix
23        24          878243     Microvix
24        25          878244     Microvix
25        26          878245     Microvix
26        27          878246     Microvix
27        28         2031527           UX
28        29         2050988           UX
29        30         2098521           UX
..       ...             ...          ...
79        80         1213619      Rezende
80        81         1213621      Rezende
81        82         1213622      Rezende
82        83         1213623      Rezende
83        84         1213624      Rezende
84        85         1213625      Rezende
85        86         2182292      Rezende
86        87         2182293      Rezende
87        88         2182294      Rezende
88        89         2182295      Rezende
89        90         2182296      Rezende
90        91         2182297      Rezende
91        92         2182298      Rezende
92        93         1013762          BIG
93        94         1013763          BIG
94        95         1013764          BIG
95        96         1013765          BIG
96        97         1013766          BIG
97        98         1013767          BIG
98        99         1013768          BIG
99       100         1013769          BIG
100      101         1013770          BIG
101      102         1013771          BIG
102      103         1933985          BIG
103      104         2183984          BIG
104      105         2211250       Seller
105      106         2211251       Seller
106      107         2211262       Seller
107      108         2211260       Seller
108      109         2360714         MIDe

                                    item_name       item_vertical
0                      Tempo MID_central_5min                 MID
1                         Tempo MID6_ral_5min                 MID
2                 Tempo MID4_centcentral_5min                 MID
3                     Tempo MID5_central_5min                 MID
4               Contingencia_MIDCentral_60min                 MID
5                Contingencia_MID_mide6_60min                 MID
6                           Offline_MID_mide6                 MID
7          Contingencia_MID_azure_mide4_60min                 MID
8          Contingencia_MID_azure_mide5_60min                 MID
9              Tempo Autorizacao (LINX + ADQ)  Meios de Pagamento
10                         Tempo ERP Microvix            Shopping
11                         Tempo POS Microvix            Shopping
12               Tempo SincronizaÃ§Ã£o do PDV            Shopping
13                    Transacional MVX PROD1             Shopping
14                    Transacional MVX PROD2             Shopping
15                   Transacional MVX PROD3              Shopping
16                   Transacional MVX PROD4              Shopping
17                   Transacional MVX PROD5              Shopping
18                   Transacional MVX PROD6              Shopping
19                   Transacional MVX PROD7              Shopping
20                   Transacional MVX PROD8              Shopping
21                   Transacional MVX PROD9              Shopping
22                  Transacional MVX PROD10              Shopping
23                  Transacional MVX PROD11              Shopping
24                  Transacional MVX PROD12              Shopping
25                  Transacional MVX PROD13              Shopping
26                   Transacional MVX PROD14             Shopping
27        Tempo Aut UX - Autenticacao - Azure            Shopping
28           Tempo Aut UX - Atenticacao - AMC            Shopping
29           Tempo Aut UX - Atenticacao - DLG            Shopping
..                                        ...                 ...
79           Tempo LM15-B3-EMSYS: Performance              Postos
80        Tempo XCH01-PG02-EMSYS: Performance              Postos
81        Tempo XCH01-PG03-EMSYS: Performance              Postos
82        Tempo XCH01-PG04-EMSYS: Performance              Postos
83        Tempo XCH01-PG05-EMSYS: Performance              Postos
84        Tempo XCH01-PG06-EMSYS: Performance              Postos
85   Tempo emsysprd-vppg01-EMSYS: Performance              Postos
86   Tempo emsysprd-vppg02-EMSYS: Performance              Postos
87   Tempo emsysprd-vppg03-EMSYS: Performance              Postos
88   Tempo emsysprd-vppg04-EMSYS: Performance              Postos
89   Tempo emsysprd-vppg05-EMSYS: Performance              Postos
90   Tempo emsysprd-vppg06-EMSYS: Performance              Postos
91   Tempo emsysprd-vppg07-EMSYS: Performance              Postos
92               Tempo LNXBIGWEB08-BIGCONECTA               Farma
93               Tempo LNXBIGWEB09-BIGCONECTA               Farma
94               Tempo LNXBIGWEB07-BIGCONECTA               Farma
95               Tempo LNXBIGWEB10-BIGCONECTA               Farma
96               Tempo LNXBIGWEB11-BIGCONECTA               Farma
97                Tempo LNXBIGDB07-BIGCONECTA               Farma
98                Tempo LNXBIGDB08-BIGCONECTA               Farma
99                Tempo LNXBIGDB09-BIGCONECTA               Farma
100               Tempo LNXBIGDB10-BIGCONECTA               Farma
101               Tempo LNXBIGDB11-BIGCONECTA               Farma
102               Tempo LNXBIGDB16-BIGCONECTA               Farma
103               Tempo LNXBIGDB18-BIGCONECTA               Farma
104                       Tempo Login Seller               Postos
105             Tempo Seller Consultar Vendas              Postos
106         Tempo Seller lancamento de Vendas              Postos
107     Tempo Seller Livro de Movimento Caixa              Postos
108                         Tempo MIDevo 5min                 MID

[109 rows x 5 columns]

In [26]:
n = 0
count_row = df.shape[0] 


while  n < count_row:
    
    item_id = df.loc[n, 'item_id']
    print(item_id)
    
    item_id_zabbix = df['item_id_zabbix'].loc[n]
    item = int(item_id_zabbix)
    #item = 878242
    print(item_id_zabbix)
    
    item_produto = df['item_produto'].loc[n]
    print(item_produto)
    
    
    historico = zapi.history.get({ 'itemids': [ item ], 
                                  'history': 0, 
                                  'output': 'extend', 
                                  'time_from': time_from, 
                                 }) 

    for point in historico:       
        dtItem = ("{0}".format(datetime.fromtimestamp(int(point['clock'])).strftime("%x %X"), point['value']))
        valorItem = ('{1}'.format(datetime.fromtimestamp(int(point['clock'])).strftime("%x %X"), point['value']))
        
    print(dtItem)

    #vi = valorItem.replace('.' , ',')

    vi = float(valorItem)
    print(vi)
        
    # Inserir os dados na tabela (preferivel já ter mapeada)
    cursor.execute("INSERT INTO tb_kpi(tb_item_item_id, kpi_valor, kpi_dttime) VALUES('" + str(item_id) + "','" + str(vi) + "','" + str(dtItem) + "')")
    print("Inserted",cursor.rowcount,"row(s) of data.")
    

    print('----------------------------------------------------')
    n = n + 1

1
2212476
MIDe
01/10/19 14:58:14
5.84
Inserted 1 row(s) of data.
----------------------------------------------------
2
2212479
MIDe
01/10/19 14:58:39
1460.0
Inserted 1 row(s) of data.
----------------------------------------------------
3
2212481
MIDe
01/10/19 14:58:41
1983.0
Inserted 1 row(s) of data.
----------------------------------------------------
4
2212483
MIDe
01/10/19 14:58:44
2027.0
Inserted 1 row(s) of data.
----------------------------------------------------
5
2198455
MIDe
01/10/19 14:58:56
1.28
Inserted 1 row(s) of data.
----------------------------------------------------
6
2198498
MIDe
01/10/19 14:59:38
0.35
Inserted 1 row(s) of data.
----------------------------------------------------
7
2199995
MIDe
01/10/19 14:59:35
29.0
Inserted 1 row(s) of data.
----------------------------------------------------
8
2198369
MIDe
01/10/19 14:59:30
0.27
Inserted 1 row(s) of data.
----------------------------------------------------
9
2198412
MIDe
01/10/19 14:59:12
0.15
Inserted 1 row(s) of data.
----------------------------------------------------
10
2003427
DTEF
01/10/19 14:59:12
0.15
Inserted 1 row(s) of data.
----------------------------------------------------
11
917847
Microvix
01/10/19 14:58:50
0.3881
Inserted 1 row(s) of data.
----------------------------------------------------
12
2156697
Microvix
01/10/19 14:57:36
0.3552
Inserted 1 row(s) of data.
----------------------------------------------------
13
2184022
Microvix
01/10/19 14:57:36
0.3552
Inserted 1 row(s) of data.
----------------------------------------------------
14
878233
Microvix
01/10/19 14:58:14
5.99
Inserted 1 row(s) of data.
----------------------------------------------------
15
878234
Microvix
01/10/19 14:58:14
6.85
Inserted 1 row(s) of data.
----------------------------------------------------
16
878235
Microvix
01/10/19 14:58:14
6.27
Inserted 1 row(s) of data.
----------------------------------------------------
17
878236
Microvix
01/10/19 14:58:14
5.78
Inserted 1 row(s) of data.
----------------------------------------------------
18
878237
Microvix
01/10/19 14:58:14
6.2
Inserted 1 row(s) of data.
----------------------------------------------------
19
878238
Microvix
01/10/19 14:58:14
6.09
Inserted 1 row(s) of data.
----------------------------------------------------
20
878239
Microvix
01/10/19 14:58:14
6.17
Inserted 1 row(s) of data.
----------------------------------------------------
21
878240
Microvix
01/10/19 14:58:14
6.48
Inserted 1 row(s) of data.
----------------------------------------------------
22
878241
Microvix
01/10/19 14:58:14
6.2
Inserted 1 row(s) of data.
----------------------------------------------------
23
878242
Microvix
01/10/19 14:58:14
5.84
Inserted 1 row(s) of data.
----------------------------------------------------
24
878243
Microvix
01/10/19 14:58:14
6.47
Inserted 1 row(s) of data.
----------------------------------------------------
25
878244
Microvix
01/10/19 14:58:14
6.06
Inserted 1 row(s) of data.
----------------------------------------------------
26
878245
Microvix
01/10/19 14:58:14
6.18
Inserted 1 row(s) of data.
----------------------------------------------------
27
878246
Microvix
01/10/19 14:58:14
6.13
Inserted 1 row(s) of data.
----------------------------------------------------
28
2031527
UX
01/10/19 14:59:58
0.8608
Inserted 1 row(s) of data.
----------------------------------------------------
29
2050988
UX
01/10/19 14:58:19
0.8381
Inserted 1 row(s) of data.
----------------------------------------------------
30
2098521
UX
01/10/19 14:59:55
0.8901
Inserted 1 row(s) of data.
----------------------------------------------------
31
2098515
UX
01/10/19 14:58:21
0.9098
Inserted 1 row(s) of data.
----------------------------------------------------
32
2031579
UX
01/10/19 14:59:20
1.0977
Inserted 1 row(s) of data.
----------------------------------------------------
33
2050982
UX
01/10/19 14:58:20
1.1044
Inserted 1 row(s) of data.
----------------------------------------------------
34
2098496
UX
01/10/19 14:59:21
1.0273
Inserted 1 row(s) of data.
----------------------------------------------------
35
2098508
UX
01/10/19 14:59:00
1.1269
Inserted 1 row(s) of data.
----------------------------------------------------
36
2031567
UX
01/10/19 14:55:23
0.7316
Inserted 1 row(s) of data.
----------------------------------------------------
37
2050975
UX
01/10/19 14:58:07
0.7871
Inserted 1 row(s) of data.
----------------------------------------------------
38
2098563
UX
01/10/19 14:56:09
0.7736
Inserted 1 row(s) of data.
----------------------------------------------------
39
2098575
UX
01/10/19 15:00:25
0.7377
Inserted 1 row(s) of data.
----------------------------------------------------
40
1970492
Analytics
01/10/19 14:55:47
0.1453
Inserted 1 row(s) of data.
----------------------------------------------------
41
1970501
Analytics
01/10/19 14:55:48
0.2022
Inserted 1 row(s) of data.
----------------------------------------------------
42
1970495
Analytics
01/10/19 14:55:47
0.2039
Inserted 1 row(s) of data.
----------------------------------------------------
43
1879138
OPUS
01/10/19 14:56:31
0.2568
Inserted 1 row(s) of data.
----------------------------------------------------
44
1879174
OPUS
01/10/19 14:56:33
0.7624
Inserted 1 row(s) of data.
----------------------------------------------------
45
1879375
OPUS
01/10/19 14:56:49
0.3961
Inserted 1 row(s) of data.
----------------------------------------------------
46
1879411
OPUS
01/10/19 14:56:52
0.3778
Inserted 1 row(s) of data.
----------------------------------------------------
47
1956402
OPUS
01/10/19 14:56:56
0.2565
Inserted 1 row(s) of data.
----------------------------------------------------
48
1956426
OPUS
01/10/19 14:56:58
0.3884
Inserted 1 row(s) of data.
----------------------------------------------------
49
1956450
OPUS
01/10/19 14:56:59
0.4165
Inserted 1 row(s) of data.
----------------------------------------------------
50
1879144
OPUS
01/10/19 14:56:32
0.6572
Inserted 1 row(s) of data.
----------------------------------------------------
51
1879180
OPUS
01/10/19 14:56:33
0.3056
Inserted 1 row(s) of data.
----------------------------------------------------
52
1879381
OPUS
01/10/19 14:56:51
0.5242
Inserted 1 row(s) of data.
----------------------------------------------------
53
1879417
OPUS
01/10/19 14:56:54
0.375
Inserted 1 row(s) of data.
----------------------------------------------------
54
1956408
OPUS
01/10/19 14:56:57
0.5717
Inserted 1 row(s) of data.
----------------------------------------------------
55
1956456
OPUS
01/10/19 14:56:59
0.2518
Inserted 1 row(s) of data.
----------------------------------------------------
56
1879150
OPUS
01/10/19 14:57:06
0.2563
Inserted 1 row(s) of data.
----------------------------------------------------
57
1879186
OPUS
01/10/19 14:56:47
0.2636
Inserted 1 row(s) of data.
----------------------------------------------------
58
1879387
OPUS
01/10/19 14:56:51
0.2631
Inserted 1 row(s) of data.
----------------------------------------------------
59
1879423
OPUS
01/10/19 14:56:55
0.3746
Inserted 1 row(s) of data.
----------------------------------------------------
60
1956414
OPUS
01/10/19 14:56:57
0.6642
Inserted 1 row(s) of data.
----------------------------------------------------
61
1956462
OPUS
01/10/19 14:57:00
0.7617
Inserted 1 row(s) of data.
----------------------------------------------------
62
2089008
Degust
01/10/19 14:56:49
1.0933
Inserted 1 row(s) of data.
----------------------------------------------------
63
2089007
Degust
01/10/19 14:56:48
0.1238
Inserted 1 row(s) of data.
----------------------------------------------------
64
2089006
Degust
01/10/19 14:56:46
0.1229
Inserted 1 row(s) of data.
----------------------------------------------------
65
2089005
Degust
01/10/19 14:56:45
0.1209
Inserted 1 row(s) of data.
----------------------------------------------------
66
2089004
Degust
01/10/19 14:56:44
0.3749
Inserted 1 row(s) of data.
----------------------------------------------------
67
2089087
Degust
01/10/19 14:58:07
0.1298
Inserted 1 row(s) of data.
----------------------------------------------------
68
2089086
Degust
01/10/19 14:58:06
0.1242
Inserted 1 row(s) of data.
----------------------------------------------------
69
2089085
Degust

01/10/19 14:58:06
0.1228
Inserted 1 row(s) of data.
----------------------------------------------------
70
2089084
Degust
01/10/19 14:58:05
0.1186
Inserted 1 row(s) of data.
----------------------------------------------------
71
2089083
Degust
01/10/19 14:58:04
0.3844
Inserted 1 row(s) of data.
----------------------------------------------------
72
878353
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
73
878354
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
74
878356
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
75
878358
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
76
878360
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
77
878366
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
78
1213617
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
79
1213618
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
80
1213619
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
81
1213621
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
82
1213622
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
83
1213623
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
84
1213624
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
85
1213625
Rezende
01/10/19 14:58:14
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
86
2182292
Rezende
01/10/19 15:01:14
0.29
Inserted 1 row(s) of data.
----------------------------------------------------
87
2182293
Rezende
01/10/19 15:01:14
0.39
Inserted 1 row(s) of data.
----------------------------------------------------
88
2182294
Rezende
01/10/19 15:01:14
0.18
Inserted 1 row(s) of data.
----------------------------------------------------
89
2182295
Rezende
01/10/19 15:01:14
0.31
Inserted 1 row(s) of data.
----------------------------------------------------
90
2182296
Rezende
01/10/19 15:01:14
0.2
Inserted 1 row(s) of data.
----------------------------------------------------
91
2182297
Rezende
01/10/19 15:01:14
0.18
Inserted 1 row(s) of data.
----------------------------------------------------
92
2182298
Rezende
01/10/19 15:01:14
0.2
Inserted 1 row(s) of data.
----------------------------------------------------
93
1013762
BIG
01/10/19 15:01:14
0.43
Inserted 1 row(s) of data.
----------------------------------------------------
94
1013763
BIG
01/10/19 15:01:14
0.78
Inserted 1 row(s) of data.
----------------------------------------------------
95
1013764
BIG
01/10/19 15:01:14
0.5
Inserted 1 row(s) of data.
----------------------------------------------------
96
1013765
BIG
01/10/19 15:01:14
0.59
Inserted 1 row(s) of data.
----------------------------------------------------
97
1013766
BIG
01/10/19 15:01:14
0.61
Inserted 1 row(s) of data.
----------------------------------------------------
98
1013767
BIG
01/10/19 15:01:14
0.55
Inserted 1 row(s) of data.
----------------------------------------------------
99
1013768
BIG
01/10/19 15:01:14
0.48
Inserted 1 row(s) of data.
----------------------------------------------------
100
1013769
BIG
01/10/19 15:01:14
0.85
Inserted 1 row(s) of data.
----------------------------------------------------
101
1013770
BIG
01/10/19 15:01:14
0.62
Inserted 1 row(s) of data.
----------------------------------------------------
102
1013771
BIG
01/10/19 15:01:14
0.67
Inserted 1 row(s) of data.
----------------------------------------------------
103
1933985
BIG
01/10/19 15:01:14
0.56
Inserted 1 row(s) of data.
----------------------------------------------------
104
2183984
BIG
01/10/19 15:01:14
0.47
Inserted 1 row(s) of data.
----------------------------------------------------
105
2211250
Seller
01/10/19 14:59:11
1.12
Inserted 1 row(s) of data.
----------------------------------------------------
106
2211251
Seller
01/10/19 14:59:12
5.1
Inserted 1 row(s) of data.
----------------------------------------------------
107
2211262
Seller
01/10/19 14:59:23
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
108
2211260
Seller
01/10/19 14:59:21
0.0
Inserted 1 row(s) of data.
----------------------------------------------------
109
2360714
MIDe
01/10/19 15:01:14
582.0
Inserted 1 row(s) of data.
----------------------------------------------------

In [11]:
print(item)
type(item)

2212476

int

In [27]:
# Cleanup

conn.commit()
cursor.close()
conn.close()

print("Connection finished")
print("Done.")

Connection finished
Done.